DROP TABLE ABS_DATA


CREATE TABLE ABS_CLEAN (
  PopulationID VARCHAR(50) NOT NULL,
  POPULATION INT,
  RegionID VARCHAR(100) NOT NULL,
  RegionName VARCHAR(100) NOT NULL,
PRIMARY KEY (POPULATIONID));

SELECT * FROM ABS_CLEAN