DROP TABLE ABS_CLEAN

CREATE TABLE ABS_CLEAN (
   PopulationID int NOT NULL,
   Population int NOT NULL,
   RegionID vARCHAR(255) NOT NULL PRIMARY KEY,
   RegionName VARCHAR(255) NOT NULL);


SELECT * FROM ABS_CLEAN

CREATE TABLE LGA_CLEAN (
   LGAID int NOT NULL,
   LGA_CODE_2020 int NOT NULL PRIMARY KEY,
   LGA_NAME_2020 VARCHAR(255) NOT NULL,
   AREA_ALBERS_SQKM VARCHAR(255) NOT NULL);

SELECT * FROM LGA_CLEAN


CREATE TABLE COVID_CLEAN (
   PatientID int NOT NULL PRIMARY KEY,
   Diagnosis_date VARCHAR (255) NOT NULL,
   Postcode VARCHAR(255) NOT NULL,
   acquired VARCHAR(255) NOT NULL,
   Localgovernmentarea VARCHAR(255) NOT NULL,
   Year VARCHAR (255) NOT NULL, 
   Month VARCHAR (255) NOT NULL);


